# Generated by Django 4.1.5 on 2023-01-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(default='', max_length=200),
        ),
    ]
